### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by kawaiicheese** [gucci-ninja/crowdsink#1]
Repository was created before the name was finalized. crowdsync is also a potential name for us.
As well, the repository should be in camelCase so "crowdSink" should be the name to prevent confusion of the name being "crowds-ink".

**Comment by kawaiicheese** [comment]
In reflection of recent discussions, I believe that we should change the name instead to something using hyphens, for example "crowd-sink". The issue will stay open until fixed

**Comment by gucci-ninja** [comment]
Hi Joseph, I thought upon our in person discussion the issue had been resolved. it is uncommon to use camelCase for repository names. I believe crowdsink is supposed to be a word play on the term crowdsource. Since it is a single word, we are sticking with a single word. For further clarification we can add a logo to distinguish that it is crowd sink and not crowds ink. Thanks
